trainer:
  name: Trainer
  num_epochs: 13
  model_dir: ./model/ResNet152

dataset:
  name: MNIST
  batch_size: 64

model:
  name: ResNet
  arch: 152 #18, 34, 50, 101, 152
  num_classes: 10

# model: 
#   name: MobileNetV3
#   num_classes: 10

optimizer:
  name: Adam
  lr: 1.e-3

scheduler:
  name: StepLR
  step_size: 4
