trainer:
  name: Trainer
  num_epochs: 20
  model_dir: ./model/ResNet18

dataset:
  name: MNIST
  batch_size: 64

model:
  name: ResNet
  arch: 18
        #18, 34, 50, 101, 152

optimizer:
  name: Adam
  lr: 1.e-3

scheduler:
  name: StepLR
  step_size: 10
